### ISSUE TITLE
在分布式情况下，使用paddle.save无法保存模型且未生成模型文件

### ISSUE THREAD

**Issue by boboboss-cmd** [PaddlePaddle/PaddleFleetX#1016]
![image](https://user-images.githubusercontent.com/52617714/210915119-6c1c2451-3f71-4e9e-bbc0-130156f1781b.png)
![image](https://user-images.githubusercontent.com/52617714/210915320-4b4c5ee2-e447-49b2-9b8c-7d221efada93.png)

**Comment by GuoxiaWang** [comment]
`model.weight` 改成 `model.state_dict()` 试试?
