### ISSUE TITLE
在paddlefleet分布式模型训练的情况下，使用collective模型时，模型的保存和加载方式是如何实现的？

### ISSUE THREAD

**Issue by boboboss-cmd** [PaddlePaddle/PaddleFleetX#1019]

**Comment by GuoxiaWang** [comment]
目前是各自卡保存自己的模型，参考 https://github.com/PaddlePaddle/PaddleFleetX/blob/5c7a3b5d6ef1ae8c618f278f3737988609772a96/ppfleetx/core/engine/eager_engine.py#L652

**Comment by boboboss-cmd** [comment]
> 目前是各自卡保存自己的模型，参考
> 
> https://github.com/PaddlePaddle/PaddleFleetX/blob/5c7a3b5d6ef1ae8c618f278f3737988609772a96/ppfleetx/core/engine/eager_engine.py#L652

谢谢你的回答，我使用的是k8s加docker的形式，我给每个卡都建立了各自的保存目录，但是结果只有一个目录中保存了模型；我想将模型再次加载后继续训练，但是总是在第一次保存后再次加载进行训练的时候就会卡住或者无法加载，提示的结果只显示了‘INFO’这个这个标识

**Comment by GuoxiaWang** [comment]
可以贴一下 log 日志

**Comment by GuoxiaWang** [comment]
对了， 你用的是什么并行策略，纯 DP 吗？

**Comment by boboboss-cmd** [comment]
> 对了， 你用的是什么并行策略，纯 DP 吗？

我并没有设置策略，只设置这两句：
paddle.set_device("gpu") 
fleet.init(is_collective=True)
然后将模型和优化器放入了model = fleet.distributed_model(model)和optimizer = fleet.distributed_optimizer(optimizer)中

**Comment by boboboss-cmd** [comment]
> 可以贴一下 log 日志
日志如下
![image](https://user-images.githubusercontent.com/52617714/211520059-c4f0c6d0-6943-450b-aefb-719b7e5e13e0.png)

**Comment by haohongxiang** [comment]
> > 对了， 你用的是什么并行策略，纯 DP 吗？
> 
> 我并没有设置策略，只设置这两句： paddle.set_device("gpu") fleet.init(is_collective=True) 然后将模型和优化器放入了model = fleet.distributed_model(model)和optimizer = fleet.distributed_optimizer(optimizer)中

如果没有设置并行策略，那么默认是数据并行策略。每张卡有相同的参数和优化器状态，只需要保存一份即可（一般选择卡0做保存），而加载的话每张卡都加载卡0保存的就行。

**Comment by boboboss-cmd** [comment]
> > > 对了， 你用的是什么并行策略，纯 DP 吗？
> > 
> > 
> > 我并没有设置策略，只设置这两句： paddle.set_device("gpu") fleet.init(is_collective=True) 然后将模型和优化器放入了model = fleet.distributed_model(model)和optimizer = fleet.distributed_optimizer(optimizer)中
> 
> 如果没有设置并行策略，那么默认是数据并行策略。每张卡有相同的参数和优化器状态，只需要保存一份即可（一般选择卡0做保存），而加载的话每张卡都加载卡0保存的就行。

请教一下，我有个疑问，在用paddle.save保存了模型参数和优化器参数后，为什么使用paddle.load这个api再将参数加载进模型时，load api没有发挥效果

**Comment by GuoxiaWang** [comment]
不会呀， paddle.load 只是把参数从文件加载到程序中，具体要设置到模型中，还需要自己设置的。

**Comment by boboboss-cmd** [comment]
> 不会呀， paddle.load 只是把参数从文件加载到程序中，具体要设置到模型中，还需要自己设置的。
我是这样操作的
![image](https://user-images.githubusercontent.com/52617714/211712688-9df1d823-1a5b-431a-8edb-3f7e94504494.png)

**Comment by GuoxiaWang** [comment]
你这里是加载预训练进行fintune 还是 resume 热启继续训练？

**Comment by boboboss-cmd** [comment]
> 你这里是加载预训练进行fintune 还是 resume 热启继续训练？

是整个训练完了，然后使用另个数据集，想使用上个数据集产生的模型参数对这个新的数据进行训练

**Comment by GuoxiaWang** [comment]
那是不是参数名称不匹配呀。检查一下。按道理不匹配是要打印的。 不过你这边打印确认一下， 加载进来的模型 dict 中参数名称和你要set 的模型的参数名称是否一致

**Comment by boboboss-cmd** [comment]
> 那是不是参数名称不匹配呀。检查一下。按道理不匹配是要打印的。 不过你这边打印确认一下， 加载进来的模型 dict 中参数名称和你要set 的模型的参数名称是否一致

感谢感谢，解决了，就是在过程中没有仔细看加载的路径问题

**Comment by GuoxiaWang** [comment]
好的
