### ISSUE TITLE
paddle fleet 我用distribute_transpiler模式训练，我想把embeding 固定 住。报错

### ISSUE THREAD

**Issue by zle1992** [PaddlePaddle/PaddleFleetX#171]
paddle fleet 我用distribute_transpiler模式训练，我想把embeding 固定住，trainable=False，训练的时候报错说embeding 没有初始化。trainable改成true就没问题了，可以帮忙看下嘛？
<img width="1280" alt="82991b0195420d1e04368be78bb5d558" src="https://user-images.githubusercontent.com/16644339/80305709-0e007300-87f1-11ea-8908-3b80acdb70c1.png">

**Comment by seiriosPlus** [comment]
trainable=False这块有问题修复.

当前解决方法：
1.trainable=True，但设置学习率为0.
2. 每一个trainer本地重新初始化(load_variable)一下emb。

**Comment by zle1992** [comment]
> load_variable

设置成0了，训练了一会报下面的错误 
![image](https://user-images.githubusercontent.com/16644339/80310537-cf2ce600-880d-11ea-94f6-1a09101c2777.png)

**Comment by zle1992** [comment]
> trainable=False这块有问题修复.
> 
> 当前解决方法：
> 1.trainable=True，但设置学习率为0.
> 2. 每一个trainer本地重新初始化(load_variable)一下emb。

第二种方法可以详细说下嘛
