### ISSUE TITLE
多卡训练时做多卡评估

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/PaddleFleetX#210]
现在Fleet可以支持 多卡训练的时候做**多卡**评估么?
之前记得涉及到allreduce的事情代码量很繁琐，现在有新的方案or简洁的代码示例么？
谢谢

**Comment by gavin1332** [comment]
可以的，我稍后提供一个示例代码出来！

**Comment by gavin1332** [comment]
https://github.com/PaddlePaddle/Fleet/pull/214/files

**Comment by gavin1332** [comment]
@shippingwang 可以关注下上述PR

**Comment by shippingwang** [comment]
> @shippingwang 可以关注下上述PR

OK

**Comment by gavin1332** [comment]
代码已经合入 @shippingwang

**Comment by gavin1332** [comment]
先关闭issue，如果有新的问题，欢迎找我咨询
