### ISSUE TITLE
Fleet会开源其源码吗

### ISSUE THREAD

**Issue by tomcheng0618** [PaddlePaddle/PaddleFleetX#215]
Fleet是否能够开放其分布式参数服务器代码，我们希望基于参数服务器开发一些op

**Comment by guru4elephant** [comment]
> Fleet是否能够开放其分布式参数服务器代码，我们希望基于参数服务器开发一些op

参数服务器相关的op没有在API层面暴露给用户，请问具体的需求是什么，可以私聊

**Comment by tomcheng0618** [comment]
可否留以下邮箱，我给您发邮件

**Comment by guru4elephant** [comment]
dongdaxiang@baidu.com
