### ISSUE TITLE
EMA失效

### ISSUE THREAD

**Issue by shippingwang** [PaddlePaddle/PaddleFleetX#216]
在基于Fleet开发的代码中使用EMA会失效
代码见：
https://github.com/PaddlePaddle/PaddleClas/blob/master/tools/program.py#L364 https://github.com/PaddlePaddle/PaddleClas/blob/master/tools/train.py#L119 

![image](https://user-images.githubusercontent.com/13645332/87265264-f2a22b80-c4f4-11ea-84ee-c751a2d09da9.png)

EMA参考
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/api_cn/optimizer_cn/ExponentialMovingAverage_cn.html#exponentialmovingaverage

怀疑是distributed_optimizer的问题....

**Comment by guru4elephant** [comment]
看起来是的，默认的选项会把program直接转为compiled program，并保存在fleet.main_program中，所以minimize之后的操作不没有更新到计算图中。可以尝试如下选项试试
``` python
    dist_strategy.mode = "collective"
    dist_strategy.collective_mode = "grad_allreduce"
```
@shippingwang

**Comment by shippingwang** [comment]
> 看起来是的，默认的选项会把program直接转为compiled program，并保存在fleet.main_program中，所以minimize之后的操作不没有更新到计算图中。可以尝试如下选项试试
> 
> ```python
>     dist_strategy.mode = "collective"
>     dist_strategy.collective_mode = "grad_allreduce"
> ```
> 
> @shippingwang

好的👍 可以更新了

![36b2b2816fab04b72bea3dbca4d7e3b3](https://user-images.githubusercontent.com/13645332/87265364-35fc9a00-c4f5-11ea-829d-545dfcc87a1f.png)


精度上我再对下

**Comment by guru4elephant** [comment]
好的，可以把结论发到这里@shippingwang

**Comment by gavin1332** [comment]
@shippingwang 上述解答是否解决了你的问题？

**Comment by shippingwang** [comment]
> @shippingwang 上述解答是否解决了你的问题？

精度还在验证，可能要下周末才有结论，之后我再及时更新这个issue
