### ISSUE TITLE
Fleet/examples/distribute_ctr/local_cluster.sh  ERROR---原始demo报错

### ISSUE THREAD

**Issue by starsblinking** [PaddlePaddle/PaddleFleetX#222]
run: sh local_cluster.sh async
get error:
/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/executor.py:1070: UserWarning: The following exception is not an EOF exception.
  "The following exception is not an EOF exception.")
Traceback (most recent call last):
  File "async_train.py", line 116, in <module>
    train(params)
  File "async_train.py", line 108, in train
    fluid.io.save_persistables(executor=exe, dirname=model_path)
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/io.py", line 647, in save_persistables
    filename=filename)
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/io.py", line 301, in save_vars
    filename=filename)
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/io.py", line 356, in save_vars
    executor.run(save_program)
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1071, in run
    six.reraise(*sys.exc_info())
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1066, in run
    return_merged=return_merged)
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1154, in _run_impl
    use_program_cache=use_program_cache)
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/executor.py", line 1229, in _run_program
    fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet:

--------------------------------------------
C++ Call Stacks (More useful to developers):
--------------------------------------------
0   std::string paddle::platform::GetTraceBackString<std::string const&>(std::string const&, char const*, int)
1   paddle::platform::EnforceNotMet::EnforceNotMet(std::string const&, char const*, int)
2   paddle::framework::OperatorWithKernel::ParseInputDataType(paddle::framework::ExecutionContext const&, std::string const&, paddle::framework::proto::VarType_Type*) const
3   paddle::framework::OperatorWithKernel::IndicateVarDataType(paddle::framework::ExecutionContext const&, std::string const&) const
4   paddle::operators::SaveOp::GetExpectedKernelType(paddle::framework::ExecutionContext const&) const
5   paddle::framework::OperatorWithKernel::ChooseKernel(paddle::framework::RuntimeContext const&, paddle::framework::Scope const&, paddle::platform::Place const&) const
6   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&, paddle::framework::RuntimeContext*) const
7   paddle::framework::OperatorWithKernel::RunImpl(paddle::framework::Scope const&, paddle::platform::Place const&) const
8   paddle::framework::OperatorBase::Run(paddle::framework::Scope const&, paddle::platform::Place const&)
9   paddle::framework::Executor::RunPartialPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, long, long, bool, bool, bool)
10  paddle::framework::Executor::RunPreparedContext(paddle::framework::ExecutorPrepareContext*, paddle::framework::Scope*, bool, bool, bool)
11  paddle::framework::Executor::Run(paddle::framework::ProgramDesc const&, paddle::framework::Scope*, int, bool, bool, std::vector<std::string, std::allocator<std::string> > const&, bool, bool)

------------------------------------------
Python Call Stacks (More useful to users):
------------------------------------------
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/framework.py", line 2610, in append_op
    attrs=kwargs.get("attrs", None))
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/io.py", line 327, in save_vars
    attrs={'file_path': os.path.normpath(save_file_path)})
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/io.py", line 301, in save_vars
    filename=filename)
  File "/home/XXX/apps/anaconda3/envs/paddle2/lib/python2.7/site-packages/paddle/fluid/io.py", line 647, in save_persistables
    filename=filename)
  File "async_train.py", line 108, in train
    fluid.io.save_persistables(executor=exe, dirname=model_path)
  File "async_train.py", line 116, in <module>
    train(params)

----------------------
Error Message Summary:
----------------------
InvalidArgumentError: The Tensor in the save Op's Input Variable X(SparseFeatFactors) is not initialized.
  [Hint: Expected t->IsInitialized() == true, but received t->IsInitialized():0 != true:1.] at (/paddle/paddle/fluid/framework/operator.cc:1289)
  [operator < save > error]
pure virtual method called
terminate called without an active exception
W0720 16:02:18.644717 457584 init.cc:216] Warning: PaddlePaddle catches a failure signal, it may not work properly
W0720 16:02:18.644743 457584 init.cc:218] You could check whether you killed PaddlePaddle thread/process accidentally or report the case to PaddlePaddle
W0720 16:02:18.644749 457584 init.cc:221] The detail failure signal is:

W0720 16:02:18.644757 457584 init.cc:224] *** Aborted at 1595232138 (unix time) try "date -d @1595232138" if you are using GNU date ***
W0720 16:02:18.647378 457584 init.cc:224] PC: @                0x0 (unknown)
W0720 16:02:18.647464 457584 init.cc:224] *** SIGABRT (@0x3f20006fa50) received by PID 457296 (TID 0x7f039d309700) from PID 457296; stack trace: ***
W0720 16:02:18.649935 457584 init.cc:224]     @     0x7f03c41b55d0 (unknown)
W0720 16:02:18.652567 457584 init.cc:224]     @     0x7f03c3706207 __GI_raise
W0720 16:02:18.655143 457584 init.cc:224]     @     0x7f03c37078f8 __GI_abort
W0720 16:02:18.656950 457584 init.cc:224]     @     0x7f03ae19c84a __gnu_cxx::__verbose_terminate_handler()
W0720 16:02:18.658381 457584 init.cc:224]     @     0x7f03ae19af47 __cxxabiv1::__terminate()
W0720 16:02:18.660149 457584 init.cc:224]     @     0x7f03ae19af7d std::terminate()
W0720 16:02:18.661695 457584 init.cc:224]     @     0x7f03ae19b988 __cxa_pure_virtual
W0720 16:02:18.667204 457584 init.cc:224]     @     0x7f03a9543a6d grpc::internal::CallOpSet<>::FinalizeResult()
W0720 16:02:18.671972 457584 init.cc:224]     @     0x7f03a95460d3 grpc::CompletionQueue::AsyncNextInternal()
W0720 16:02:18.675379 457584 init.cc:224]     @     0x7f03a9516f69 paddle::operators::distributed::GRPCClient::Proceed()
W0720 16:02:18.676784 457584 init.cc:224]     @     0x7f03ae1b7421 execute_native_thread_routine_compat
W0720 16:02:18.679189 457584 init.cc:224]     @     0x7f03c41addd5 start_thread
W0720 16:02:18.681900 457584 init.cc:224]     @     0x7f03c37cdead __clone
W0720 16:02:18.684314 457584 init.cc:224]     @                0x0 (unknown)

版本：
python=2.7.18
paddlepaddle=1.8.2
python和pd都是在anaconda下装的，服务器只有CPU。
运行单机命令python -u local_train.py --test=True &> train.log &得到的结果与README.md中的一致，能跑成功。
是不是fluid.io.save_persistables(executor=exe, dirname=model_path)这个命令在分布式下有问题呀？
咋回事呢？求解答～

**Comment by gentelyang** [comment]
将fluid.io.save_persistables替换成fleet.save_persistables试一下~

**Comment by starsblinking** [comment]
> 将fluid.io.save_persistables替换成fleet.save_persistables试一下~

That's OK. It works. 多谢!
