### ISSUE TITLE
Example code cannot run

### ISSUE THREAD

**Issue by Ruminateer** [PaddlePaddle/PaddleFleetX#440]
Environment: hub.baidubce.com/paddlepaddle/paddle:2.0.0rc1

I tried to run example code in https://github.com/PaddlePaddle/FleetX/tree/develop/examples/wide_and_deep.
Got the import error in `train.py`:
```
ImportError: No module named 'paddle.distributed.fleet.utils.ps_util'
```

Am I supposed to run the code with 2.0.0rc1?

Also, the code is different from the code in the doc https://fleet-x.readthedocs.io/paddle_fleet_rst/parameter_server/ps_quick_start.html, but according to the doc, they should be the same. I have also tried to run the code in the doc, but it doesn't work with the `model.py` in the repo.

**Comment by gentelyang** [comment]
2.0rc1后对paddle.distributed.fleet.base.util_factory进行升级，paddle.distributed.fleet.utils.ps_util不兼容2.0rc1，可将2.0rc1包替换为develop包进行训练，paddlepaddle develop包下载地址：
https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/install/Tables.html

**Comment by Ruminateer** [comment]
换成develop后解决了
(顺便现在文档里的代码因为依赖repo里的model.py所以并不工作
