### ISSUE TITLE
request for demo (paddle.distributed.split) with several embeddings in model parallel

### ISSUE THREAD

**Issue by LiuHao-THU** [PaddlePaddle/PaddleFleetX#509]
recently, when I use the FleetX to train large models with large embedding size(2000000 * 128) which is too large to fit GPU memory, when I use the demo provide by paddle using API(paddle.distributed.split), the demo runs smoothly, however, in my situation, I have several embedding need to split. so I modified the code like below. the process just stuck and no error. can someone help me solve this problem?

**code with single distributed embedding demo.**

```
import paddle

from paddle.distributed import init_parallel_env

from paddle.distributed import fleet

from paddle import nn



paddle.enable_static()

paddle.set_device('gpu:%d'%paddle.distributed.ParallelEnv().dev_id)

fleet.init(is_collective=True)



data = paddle.randint(0, 8, shape=[4,2])



embed_init = nn.initializer.Uniform(low=-1.0, high=1.0)

emb_attr = paddle.ParamAttr(initializer=embed_init, name="emb%s" % paddle.distributed.ParallelEnv().dev_id)

emb_out = paddle.distributed.split(

        data,

        (8, 8),

        operation="embedding",

        num_partitions=2,

        weight_attr=emb_attr,

        )

loss = paddle.mean(emb_out)



optimizer = paddle.fluid.optimizer.Adam(0.1)

dist_strategy = fleet.DistributedStrategy()



optimizer = fleet.distributed_optimizer(optimizer, dist_strategy)

optimizer.minimize(loss)



place = paddle.CUDAPlace(paddle.distributed.ParallelEnv().dev_id)

exe = paddle.static.Executor(place)

exe.run(paddle.static.default_startup_program())

ret = exe.run(paddle.static.default_main_program(), fetch_list=[loss.name])

print(ret)
```

**code with multiple distributed embedding demo.**

```
import paddle

from paddle.distributed import init_parallel_env

from paddle.distributed import fleet

from paddle import nn

paddle.enable_static()

paddle.set_device('gpu:%d'%paddle.distributed.ParallelEnv().dev_id)

fleet.init(is_collective=True)

data = paddle.randint(0, 8, shape=[4,2])

embed_init = nn.initializer.Uniform(low=-1.0, high=1.0)

emb_attr1 = paddle.ParamAttr(initializer=embed_init, name="emb1%s" % paddle.distributed.ParallelEnv().dev_id)
emb_attr2 = paddle.ParamAttr(initializer=embed_init, name="emb2%s" % paddle.distributed.ParallelEnv().dev_id)

emb_out1 = paddle.distributed.split(

        data,

        (8, 8),

        operation="embedding",

        num_partitions=2,

        weight_attr=emb_attr1,

        )

emb_out2 = paddle.distributed.split(

        data,

        (8, 8),

        operation="embedding",

        num_partitions=2,

        weight_attr=emb_attr2,

        )

loss = paddle.mean(emb_out1) + paddle.mean(emb_out2)



optimizer = paddle.fluid.optimizer.Adam(0.1)

dist_strategy = fleet.DistributedStrategy()



optimizer = fleet.distributed_optimizer(optimizer, dist_strategy)

optimizer.minimize(loss)



place = paddle.CUDAPlace(paddle.distributed.ParallelEnv().dev_id)

exe = paddle.static.Executor(place)

exe.run(paddle.static.default_startup_program())

ret = exe.run(paddle.static.default_main_program(), fetch_list=[loss.name])

print(ret)

```

**Comment by sandyhouse** [comment]
Please set `dist_strategy.without_graph_optimization = True` and use the paddle development branch.

**Comment by LiuHao-THU** [comment]
> Please set `dist_strategy.without_graph_optimization = True` and use the paddle development branch.

thanks for reply, I tried the demo, now the multiple version runs smoothly, however in my situation, the code still stucks, but, the valid part runs smoothly.


![IMG_0075](https://user-images.githubusercontent.com/30975916/122167345-6c812880-cead-11eb-99d8-78d42f954b58.jpeg)

**Comment by LiuHao-THU** [comment]
> Please set `dist_strategy.without_graph_optimization = True` and use the paddle development branch.

in my situation, i just replace the sparse embedding part, the code didn’t run, here is the code.
![IMG_0108](https://user-images.githubusercontent.com/30975916/122178990-aeb06700-ceb9-11eb-931e-a219c0bfe75c.jpeg)
![IMG_0109](https://user-images.githubusercontent.com/30975916/122185612-cdb1f780-cebf-11eb-9b47-da7927eed063.jpeg)
![IMG_0110](https://user-images.githubusercontent.com/30975916/122185691-e02c3100-cebf-11eb-96f4-a9c7b7306882.jpeg)

**Comment by LiuHao-THU** [comment]
> Please set `dist_strategy.without_graph_optimization = True` and use the paddle development branch.
老哥，可以➕微信聊聊吗 <luke_lh>
