### ISSUE TITLE
分布式训练，单机多卡可以跑通，多机多卡可以建立通信但是不报错也不训练

### ISSUE THREAD

**Issue by jidlin** [PaddlePaddle/PaddleFleetX#539]
### fleetrun --gpus=0,1 train_fleet_dygraph.py  正常运行

-----------  Configuration Arguments -----------
gpus: 0,1
heter_worker_num: None
heter_workers: 
http_port: None
ips: 127.0.0.1
log_dir: log
nproc_per_node: None
server_num: None
servers: 
training_script: train_fleet_dygraph.py
training_script_args: []
worker_num: None
workers: 
------------------------------------------------
WARNING 2021-09-18 15:33:48,326 launch.py:316] Not found distinct arguments and compiled with cuda. Default use collective mode
launch train in GPU mode
INFO 2021-09-18 15:33:48,328 launch_utils.py:471] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT                 127.0.0.1:25459               |
    |                     PADDLE_TRAINERS_NUM                        2                      |
    |                PADDLE_TRAINER_ENDPOINTS         127.0.0.1:25459,127.0.0.1:61055       |
    |                     FLAGS_selected_gpus                        0                      |
    +=======================================================================================+

INFO 2021-09-18 15:33:48,328 launch_utils.py:475] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
I0918 15:33:49.541898 20096 nccl_context.cc:189] init nccl context nranks: 2 local rank: 0 gpu id: 0 ring id: 0
W0918 15:33:50.633612 20096 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.2
W0918 15:33:50.636582 20096 device_context.cc:372] device: 0, cuDNN Version: 8.0.
[Epoch 0, batch 0] loss: 4.75578, acc1: 0.00000, acc5: 0.00000
[Epoch 0, batch 5] loss: 25.66356, acc1: 0.03125, acc5: 0.06250
[Epoch 0, batch 10] loss: 13.57118, acc1: 0.00000, acc5: 0.09375

### fleetrun --ips=10.130.19.203,10.130.17.157 --gpus=0,1 train_fleet_dygraph.py  卡住不运行

-----------  Configuration Arguments -----------
gpus: 0,1
heter_worker_num: None
heter_workers: 
http_port: None
ips: 10.130.19.203,10.130.17.157
log_dir: log
nproc_per_node: None
server_num: None
servers: 
training_script: train_fleet_dygraph.py
training_script_args: []
worker_num: None
workers: 
------------------------------------------------
INFO 2021-09-18 15:41:49,243 launch.py:306] Run collective gpu mode. gpu arguments:['--ips'], cuda count:2
launch train in GPU mode
INFO 2021-09-18 15:41:49,245 launch_utils.py:471] Local start 2 processes. First process distributed environment info (Only For Debug): 
    +=======================================================================================+
    |                        Distributed Envs                      Value                    |
    +---------------------------------------------------------------------------------------+
    |                       PADDLE_TRAINER_ID                        0                      |
    |                 PADDLE_CURRENT_ENDPOINT               10.130.19.203:6070              |
    |                     PADDLE_TRAINERS_NUM                        4                      |
    |                PADDLE_TRAINER_ENDPOINTS  ... 071,10.130.17.157:6070,10.130.17.157:6071|
    |                     FLAGS_selected_gpus                        0                      |
    +=======================================================================================+

INFO 2021-09-18 15:41:49,245 launch_utils.py:475] details abouts PADDLE_TRAINER_ENDPOINTS can be found in log/endpoints.log, and detail running logs maybe found in log/workerlog.0
W0918 15:41:50.323863 21635 nccl_context.cc:142] Socket connect worker 10.130.17.157:6070 failed, try again after 3 seconds.
W0918 15:41:53.324177 21635 nccl_context.cc:142] Socket connect worker 10.130.17.157:6070 failed, try again after 6 seconds.
W0918 15:41:59.324524 21635 nccl_context.cc:142] Socket connect worker 10.130.17.157:6070 failed, try again after 9 seconds.
W0918 15:42:08.324882 21635 nccl_context.cc:142] Socket connect worker 10.130.17.157:6070 failed, try again after 12 seconds.
I0918 15:42:20.325516 21635 nccl_context.cc:189] init nccl context nranks: 4 local rank: 0 gpu id: 0 ring id: 0
W0918 15:42:21.382360 21635 device_context.cc:362] Please NOTE: device: 0, GPU Compute Capability: 7.0, Driver API Version: 11.0, Runtime API Version: 10.2
W0918 15:42:21.384966 21635 device_context.cc:372] device: 0, cuDNN Version: 8.0.

**Comment by poetryben88** [comment]
你两台机器上都要执行一下这个：
fleetrun --ips=10.130.19.203,10.130.17.157 --gpus=0,1 train_fleet_dygraph.py

10.130.17.157：这台机器上执行的时候最后会有个“**listen**”提示，等待10.130.19.203这台通信。
