### ISSUE TITLE
请问fleet的recompute目前支持动态图使用吗

### ISSUE THREAD

**Issue by FesianXu** [PaddlePaddle/PaddleFleetX#542]
paddle 2.1.2中也提供了动态图的recompute支持（from paddle.distributed.fleet.utils import recompute），不过在单机多卡环境下会报错，想请问下fleet支持动态图的recompute吗，谢谢。

**Comment by youth123** [comment]
2.1版本动态图支持recompute，可以看下https://github.com/PaddlePaddle/FleetX/blob/develop/docs/source/paddle_fleet_rst/collective/collective_mp/recomputation.rst
