### ISSUE TITLE
subprocess.CalledProcessError 。。。returned non-zero exit status 1

### ISSUE THREAD

**Issue by bit-pku-zdf** [PaddlePaddle/PaddleFleetX#72]
在孔明集群中运行collective_operators，出现错误：
+ ./python2_paddle150/bin/python -m paddle.distributed.launch --selected_gpus=0,1,2,3,4,5,6,7 --log_dir mylog ./train.py --model=ResNet50 --batch_size=8 --total_images=1281167 --data_dir=./ --class_dim=100 --image_shape=3,224,224 --model_save_dir=./output --lr=0.1 --num_epochs=90 --l2_decay=1e-4 --nccl_comm_num=2 WARNING: Logging before InitGoogleLogging() is written to STDERR I1002 15:31:38.199759 1621 init.cc:67] Init commandline: dummy /home/slurm/job/tmp/job-136870/python2_paddle150/lib/python2.7/site-packages/paddle/distributed/launch.py --tryfromenv=check_nan_inf,benchmark,eager_delete_scope,initial_cpu_memory_in_mb,init_allocated_mem,free_idle_memory,paddle_num_threads,dist_threadpool_size,eager_delete_tensor_gb,fast_eager_deletion_mode,memory_fraction_of_eager_deletion,allocator_strategy,reader_queue_speed_test_mode,print_sub_graph_dir,pe_profile_fname,inner_op_parallelism,enable_parallel_graph,fuse_parameter_groups_size,multiple_of_cupti_buffer_size,fuse_parameter_memory_size,tracer_profile_fname,dygraph_debug,use_pinned_memory,cpu_deterministic,use_mkldnn,rpc_deadline,rpc_server_profile_path,enable_rpc_profiler,rpc_send_thread_num,rpc_get_thread_num,rpc_prefetch_thread_num,rpc_disable_reuse_port,communicator_independent_recv_thread,communicator_send_queue_size,communicator_min_send_grad_num_before_recv,communicator_thread_pool_size,communicator_max_merge_var_num,communicator_fake_rpc,communicator_send_wait_times,fraction_of_gpu_memory_to_use,initial_gpu_memory_in_mb,reallocate_gpu_memory_in_mb,cudnn_deterministic,enable_cublas_tensor_op_math,conv_workspace_size_limit,cudnn_exhaustive_search,selected_gpus,sync_nccl_allreduce,limit_of_tmp_allocation,times_excess_than_required_tmp_allocation,enable_inplace_whitelist,cudnn_batchnorm_spatial_persistent  Traceback (most recent call last): File "/home/slurm/job/tmp/job-136870/python2_paddle150/lib/python2.7/runpy.py", line 174, in _run_module_as_main "__main__", fname, loader, pkg_name) File "/home/slurm/job/tmp/job-136870/python2_paddle150/lib/python2.7/runpy.py", line 72, in _run_code exec code in run_globals File "/home/slurm/job/tmp/job-136870/python2_paddle150/lib/python2.7/site-packages/paddle/distributed/launch.py", line 222, in <module> launch() File "/home/slurm/job/tmp/job-136870/python2_paddle150/lib/python2.7/site-packages/paddle/distributed/launch.py", line 218, in launch start_procs(args) File "/home/slurm/job/tmp/job-136870/python2_paddle150/lib/python2.7/site-packages/paddle/distributed/launch.py", line 211, in start_procs returncode=procs[i].returncode, cmd=cmds[i]) subprocess.CalledProcessError: Command '['/home/slurm/job/tmp/job-136870/python2_paddle150/bin/python', '-u', './train.py', '--model=ResNet50', '--batch_size=8', '--total_images=1281167', '--data_dir=./', '--class_dim=100', '--image_shape=3,224,224', '--model_save_dir=./output', '--lr=0.1', '--num_epochs=90', '--l2_decay=1e-4', '--nccl_comm_num=2']' returned non-zero exit status 1 

，对于原始的demo修改了run.sh

#!/bin/bash

export LD_LIBRARY_PATH=/home/work/cuda-9.0/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=/home/work/cudnn/cudnn_v7/cuda/lib64:$LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$PWD/nccl_2.3.5/lib/:$LD_LIBRARY_PATH

export FLAGS_cudnn_exhaustive_search=0
export GLOG_v=1
export GLOG_logtostderr=1
export FLAGS_eager_delete_tensor_gb=0
export NCCL_DEBUG=INFO
# Unset proxy
unset https_proxy http_proxy
set -xe

MODEL=ResNet50 #VGG16
MODEL_SAVE_PATH="./output"

# training params
NUM_EPOCHS=90
BATCH_SIZE=8
LR=0.1

# data params
# the path of the data set
DATA_PATH="./"
TOTAL_IMAGES=1281167
CLASS_DIM=100
IMAGE_SHAPE=3,224,224

# gpu params
NCCL_COMM_NUM=2
set -x
config="--selected_gpus=0,1,2,3,4,5,6,7 --log_dir mylog"
touch ./utils/__init__.py
./python2_paddle150/bin/python -m paddle.distributed.launch ${config} \
       ./train.py \
       --model=${MODEL} \
       --batch_size=${BATCH_SIZE} \
       --total_images=${TOTAL_IMAGES} \
       --data_dir=${DATA_PATH} \
       --class_dim=${CLASS_DIM} \
       --image_shape=${IMAGE_SHAPE} \
       --model_save_dir=${MODEL_SAVE_PATH} \
       --lr=${LR} \
       --num_epochs=${NUM_EPOCHS} \
       --l2_decay=1e-4 \
       --nccl_comm_num=2 \

该脚本作为submit命令 job-script参数。
麻烦帮忙解答。

**Comment by sandyhouse** [comment]
贴一下具体训练进程的日志吧，类似mylog/workerlog.0
