### ISSUE TITLE
Can't load images.

### ISSUE THREAD

**Issue by ghost** [PaddlePaddle/PaddleFleetX#95]
Hi, I want to run the following command:
```CUDA_VISIBLE_DEVICES=0 python -m paddle.distributed.launch --selected_gpus=0 train_with_fleet.py --batch_size=128 --model=ResNet50 --total_images=50000 --data_dir=/data/PaddlePaddle/imagenet/```
but I get `'NoneType' object has no attribute 'shape'`, which means that probably images couldn't be found.

Inside `imagenet` directory I have `train_list.txt` and `train` dir, where in `train_list.txt` I point to images inside `train` direcotry. This works just fine for `PaddlePaddle/models/` repository when I run resnet50 from there. Here it doesn't work. At first I got error that `train.txt` doesn't exist, so I created it, just renamed my previous `train_list.txt`, but it still doesn't work. 

Could you clarify what the structure of the directory with dataset should look like??

**Comment by sandyhouse** [comment]
Please print the first few lines of train.txt.

**Comment by gfilipekint** [comment]
For example:
```
train/ILSVRC2012_train_00049311.JPEG 61
train/ILSVRC2012_train_00049312.JPEG 834
train/ILSVRC2012_train_00049313.JPEG 87
train/ILSVRC2012_train_00049314.JPEG 451
```

so basically
`<path> <int: category>`
is this how this file should look like?


It works just fine for `PaddlePaddle/models` as I said, seems to me that you guys use `cv2`-based reader there as well, but maybe there are some differences.

I wanted to avoid investigating it myself, hence the issue :)

**Comment by sandyhouse** [comment]
No need for the prefix 'train/', just like the following:
ILSVRC2012_train_00049311.JPEG 61
ILSVRC2012_train_00049312.JPEG 834
ILSVRC2012_train_00049313.JPEG 87
ILSVRC2012_train_00049314.JPEG 451

**Comment by gfilipekint** [comment]
So now the structure is the following:

`imagenet` directory contains:
`train.txt` file and `train` directory, where `train.txt` has just img names as you proposed, with no `train/` prefix.

Well, it doesn't work, same error as before. Deleting the prefix seems weird to me as previously `<path to train.txt>` + whatever was in `train.txt` concatenated resulted in absolute path to the image, now it doesn't because we skipped the `train` directory.

My question is - why can't there be one unified loader and dataset structure Paddle requires? Even this small change in file name, from `train_list.txt` to `train.txt` seems unnecessary to me.

**Comment by gfilipekint** [comment]
Sadly it doesn't work. I also tried running it with old structure of dataset but with the following changes in the `reader_cv2.py`:
```
if mode == 'train':
                    img_path, label = line.split()
                    #img_path = img_path.replace("JPEG", "jpeg")
                    img_path = os.path.join(data_dir, img_path)
                    yield (img_path, int(label))
```

Next week I'll launch debugger on that,  but for now could you tell me what exactly is your dataset structure? Are you able to run it no problem?

**Comment by sandyhouse** [comment]
> No need for the prefix 'train/', just like the following:
> ILSVRC2012_train_00049311.JPEG 61
> ILSVRC2012_train_00049312.JPEG 834
> ILSVRC2012_train_00049313.JPEG 87
> ILSVRC2012_train_00049314.JPEG 451

Sorry for my fault, the prefix 'train/' is needed.
In conclusion, the imagenet directory contains the train.txt file and the train directory. Each line of train.txt contains the path for an image and its corresponding label, like
train/ILSVRC2012_train_00049311.JPEG 61
train/ILSVRC2012_train_00049312.JPEG 834
train/ILSVRC2012_train_00049313.JPEG 87
train/ILSVRC2012_train_00049314.JPEG 451
